# Etapa de compilación
FROM python:3.9-slim AS builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --user --no-cache-dir -r requirements.txt

#Etapa de ejecución
FROM python:3.9-slim
WORKDIR /app
COPY --from=builder /root/.local /root/.local
ENV PATH=/root/.local/bin:$PATH

COPY app2.py requirements.txt templates/ static/ ./

EXPOSE 8181
CMD ["python3", "app2.py"]
